name: correlation
channels:
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - asn1crypto=1.3.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=mkl
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - cryptography=2.8=py37h1ba5d50_0
  - curl=7.67.0=hbc83047_0
  - decorator=4.4.1=py_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_15
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_15
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - gsl=2.4=h14c3975_4
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.16.0=py37_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.67.0=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - make=4.2.1=h1bed415_1
  - markupsafe=1.1.1=py37h7b6447c_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - more-itertools=8.2.0=py_0
  - ncurses=6.2=he6710b0_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - openssl=1.1.1d=h7b6447c_4
  - packaging=20.1=py_0
  - pandas=1.0.1=py37h0573a6f_0
  - pango=1.42.4=h049681c_0
  - parso=0.6.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h7b6447c_0
  - pluggy=0.13.1=py37_0
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.1=py_0
  - pycparser=2.19=py_0
  - pygments=2.5.2=py_0
  - pyparsing=2.4.6=py_0
  - pytest=5.3.5=py37_0
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=17.1.2=py37h14c3975_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-base=3.6.1=h9bb98a2_1
  - r-base64enc=0.1_3=r36h96ca727_4
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-bit=1.1_14=r36h96ca727_0
  - r-bit64=0.9_7=r36h96ca727_0
  - r-blob=1.1.1=r36h6115d3f_0
  - r-boot=1.3_20=r36h6115d3f_0
  - r-caret=6.0_83=r36h96ca727_0
  - r-class=7.3_15=r36h96ca727_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-cluster=2.0.8=r36ha65eedd_0
  - r-codetools=0.2_16=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h96ca727_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-curl=3.3=r36h96ca727_0
  - r-data.table=1.12.2=r36h96ca727_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h96ca727_0
  - r-dplyr=0.8.0.1=r36h29659fb_0
  - r-essentials=1.4=0
  - r-evaluate=0.13=r36h6115d3f_0
  - r-fansi=0.4.0=r36h96ca727_0
  - r-foreach=1.4.4=r36h6115d3f_0
  - r-foreign=0.8_71=r36h96ca727_0
  - r-generics=0.0.2=r36h6115d3f_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-glmnet=2.0_16=r36ha65eedd_0
  - r-glue=1.3.1=r36h96ca727_0
  - r-gower=0.2.0=r36h96ca727_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-hexbin=1.27.2=r36ha65eedd_0
  - r-highr=0.8=r36h6115d3f_0
  - r-htmltools=0.3.6=r36h29659fb_0
  - r-htmlwidgets=1.3=r36h6115d3f_0
  - r-httpuv=1.5.1=r36h29659fb_0
  - r-ipred=0.9_8=r36h96ca727_0
  - r-irdisplay=0.7.0=r36h6115d3f_0
  - r-irkernel=0.8.15=r36_0
  - r-iterators=1.0.10=r36h6115d3f_0
  - r-jsonlite=1.6=r36h96ca727_0
  - r-kernsmooth=2.23_15=r36ha65eedd_4
  - r-knitr=1.22=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_4
  - r-later=0.8.0=r36h29659fb_0
  - r-lattice=0.20_38=r36h96ca727_0
  - r-lava=1.6.5=r36h6115d3f_0
  - r-lazyeval=0.2.2=r36h96ca727_0
  - r-lubridate=1.7.4=r36h29659fb_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-maps=3.3.0=r36h96ca727_0
  - r-markdown=0.9=r36h96ca727_0
  - r-mass=7.3_51.3=r36h96ca727_0
  - r-matrix=1.2_17=r36h96ca727_0
  - r-memoise=1.1.0=r36h6115d3f_0
  - r-mgcv=1.8_28=r36h96ca727_0
  - r-mime=0.6=r36h96ca727_0
  - r-modelmetrics=1.2.2=r36h29659fb_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-nlme=3.1_139=r36ha65eedd_0
  - r-nnet=7.3_12=r36h96ca727_0
  - r-numderiv=2016.8_1=r36h6115d3f_0
  - r-pbdzmq=0.3_3=r36h29659fb_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.4=r36h29659fb_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-prodlim=2018.04.18=r36h29659fb_0
  - r-promises=1.0.1=r36h29659fb_0
  - r-purrr=0.3.2=r36h96ca727_0
  - r-quantmod=0.4_14=r36h6115d3f_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-randomforest=4.6_14=r36ha65eedd_0
  - r-rbokeh=0.6.3=r36_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h29659fb_0
  - r-rcpproll=0.3.0=r36h29659fb_0
  - r-recipes=0.1.5=r36h6115d3f_0
  - r-recommended=3.6.0=r36_0
  - r-repr=0.19.2=r36h6115d3f_0
  - r-reshape2=1.4.3=r36h29659fb_0
  - r-rlang=0.3.4=r36h96ca727_0
  - r-rmarkdown=1.12=r36h6115d3f_0
  - r-rpart=4.1_15=r36h96ca727_0
  - r-rsqlite=2.1.1=r36h29659fb_0
  - r-scales=1.0.0=r36h29659fb_0
  - r-shiny=1.3.2=r36h6115d3f_0
  - r-sourcetools=0.1.7=r36h29659fb_0
  - r-spatial=7.3_11=r36h96ca727_4
  - r-squarem=2017.10_1=r36h6115d3f_0
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-survival=2.44_1.1=r36h96ca727_0
  - r-tibble=2.1.1=r36h96ca727_0
  - r-tidyr=0.8.3=r36h29659fb_0
  - r-tidyselect=0.2.5=r36h29659fb_0
  - r-timedate=3043.102=r36h6115d3f_0
  - r-tinytex=0.12=r36h6115d3f_0
  - r-ttr=0.23_4=r36ha65eedd_0
  - r-utf8=1.1.4=r36h96ca727_0
  - r-uuid=0.1_2=r36h96ca727_4
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-withr=2.1.2=r36h6115d3f_0
  - r-xfun=0.6=r36h6115d3f_0
  - r-xtable=1.8_4=r36h6115d3f_0
  - r-xts=0.11_2=r36h96ca727_0
  - r-yaml=2.2.0=r36h96ca727_0
  - r-zoo=1.8_6=r36h96ca727_0
  - readline=7.0=h7b6447c_5
  - rpy2=2.9.4=py37r36h481b005_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=45.2.0=py37_0
  - simplegeneric=0.8.1=py37_2
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tktable=2.10=h14c3975_0
  - tornado=6.0.3=py37h7b6447c_3
  - traitlets=4.3.3=py37_0
  - tzlocal=2.0.0=py37_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - chardet==3.0.4
    - docopt==0.6.2
    - pipreqs==0.4.10
    - requests==2.23.0
    - urllib3==1.25.8
    - yarg==0.1.9
prefix: /home/phoenix/miniconda3/envs/correlation

